steps:
  # Install dependencies
  # 참고 : https://cloud.google.com/build/docs/building/build-nodejs?hl=ko
  - name: node
    entrypoint: npm
    args: 
      - run
      - 'install-all'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: 
      - '-c'
      - |
        cd client

  - name: node
    entrypoint: npm
    args: 
      - run
      - build

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: 
      - '-c'
      - |
        cd ..

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .

  # Docker push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    entrypoint: gcloud
    args: 
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'

# Store images in Google Container Registry
images:
  - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
